<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="7.10"
	Name="Surface"
	SccProjectName=""
	SccLocalPath=""
	Keyword="Win32Proj">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="Debug"
			IntermediateDirectory=".\Debug"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions="   /Zm1000       -DCMAKE_INTDIR=\&quot;Debug\&quot;"
				AdditionalIncludeDirectories="&quot;C:\Program Files\wxWidgets-2.6.3\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\include\..\contrib\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\lib\vc_lib\msw&quot;;&quot;C:\Program Files\CGAL-3.2.1\include&quot;;&quot;C:\Program Files\CGAL-3.2.1\include\CGAL\config\msvc7&quot;;&quot;C:\Program Files\CGAL-3.2.1\auxiliary\gmp\include&quot;;ism;libgm;Particles;Surface;C:\Boost\include\boost-1_33;&quot;C:\Program Files&quot;;c:\hart\wickbert\gsl;\pi;C:\hart\Wickbert;C:\hart\Wickbert\Surface;C:\hart\Wickbert\Surface\Implicit\DistanceField;C:\hart\Wickbert\Particles;C:\hart\Wickbert\Particles\Attributes;"
				BasicRuntimeChecks="1"
				DebugInformationFormat="3"
				ExceptionHandling="TRUE"
				InlineFunctionExpansion="0"
				Optimization="0"
				RuntimeLibrary="3"
				RuntimeTypeInfo="TRUE"
				WarningLevel="3"
				PreprocessorDefinitions="WIN32,_DEBUG,_WINDOWS,WINDOWS,WIN32,__WXMSW__,_USE_MATH_DEFINES,NOMINMAX,_WIN32,_HAS_ITERATOR_DEBUGGING=0,_SECURE_SCL=0,_CRT_SECURE_NO_DEPRECATE,WB_USE_CGAL,"
				AssemblerListingLocation="Debug"
				ObjectFile="Debug\"
				SuppressStartupBanner="FALSE"
				ProgramDatabaseFileName="C:/hart/Wickbert/bin/$(OutDir)/Surface.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="&quot;C:\Program Files\wxWidgets-2.6.3\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\include\..\contrib\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\lib\vc_lib\msw&quot;;&quot;C:\Program Files\CGAL-3.2.1\include&quot;;&quot;C:\Program Files\CGAL-3.2.1\include\CGAL\config\msvc7&quot;;&quot;C:\Program Files\CGAL-3.2.1\auxiliary\gmp\include&quot;;ism;libgm;Particles;Surface;C:\Boost\include\boost-1_33;&quot;C:\Program Files&quot;;c:\hart\wickbert\gsl;\pi;C:\hart\Wickbert;C:\hart\Wickbert\Surface;C:\hart\Wickbert\Surface\Implicit\DistanceField;C:\hart\Wickbert\Particles;C:\hart\Wickbert\Particles\Attributes;"
				PreprocessorDefinitions="WIN32,_DEBUG,_WINDOWS,WINDOWS,WIN32,__WXMSW__,_USE_MATH_DEFINES,NOMINMAX,_WIN32,_HAS_ITERATOR_DEBUGGING=0,_SECURE_SCL=0,_CRT_SECURE_NO_DEPRECATE,WB_USE_CGAL," />
			<Tool
				Name="VCMIDLTool"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="C:\hart\Wickbert\bin\$(OutDir)\Surface.lib."/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="Release"
			IntermediateDirectory=".\Release"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions="   /Zm1000     /D NDEBUG   /D NDEBUG -DCMAKE_INTDIR=\&quot;Release\&quot;"
				AdditionalIncludeDirectories="&quot;C:\Program Files\wxWidgets-2.6.3\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\include\..\contrib\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\lib\vc_lib\msw&quot;;&quot;C:\Program Files\CGAL-3.2.1\include&quot;;&quot;C:\Program Files\CGAL-3.2.1\include\CGAL\config\msvc7&quot;;&quot;C:\Program Files\CGAL-3.2.1\auxiliary\gmp\include&quot;;ism;libgm;Particles;Surface;C:\Boost\include\boost-1_33;&quot;C:\Program Files&quot;;c:\hart\wickbert\gsl;\pi;C:\hart\Wickbert;C:\hart\Wickbert\Surface;C:\hart\Wickbert\Surface\Implicit\DistanceField;C:\hart\Wickbert\Particles;C:\hart\Wickbert\Particles\Attributes;"
				ExceptionHandling="TRUE"
				InlineFunctionExpansion="1"
				Optimization="2"
				RuntimeLibrary="2"
				RuntimeTypeInfo="TRUE"
				WarningLevel="3"
				PreprocessorDefinitions="WIN32,_WINDOWS,WINDOWS,WIN32,__WXMSW__,_USE_MATH_DEFINES,NOMINMAX,_WIN32,_HAS_ITERATOR_DEBUGGING=0,_SECURE_SCL=0,_CRT_SECURE_NO_DEPRECATE,WB_USE_CGAL,"
				AssemblerListingLocation="Release"
				ObjectFile="Release\"
				SuppressStartupBanner="FALSE"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="&quot;C:\Program Files\wxWidgets-2.6.3\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\include\..\contrib\include&quot;;&quot;C:\Program Files\wxWidgets-2.6.3\lib\vc_lib\msw&quot;;&quot;C:\Program Files\CGAL-3.2.1\include&quot;;&quot;C:\Program Files\CGAL-3.2.1\include\CGAL\config\msvc7&quot;;&quot;C:\Program Files\CGAL-3.2.1\auxiliary\gmp\include&quot;;ism;libgm;Particles;Surface;C:\Boost\include\boost-1_33;&quot;C:\Program Files&quot;;c:\hart\wickbert\gsl;\pi;C:\hart\Wickbert;C:\hart\Wickbert\Surface;C:\hart\Wickbert\Surface\Implicit\DistanceField;C:\hart\Wickbert\Particles;C:\hart\Wickbert\Particles\Attributes;"
				PreprocessorDefinitions="WIN32,_WINDOWS,WINDOWS,WIN32,__WXMSW__,_USE_MATH_DEFINES,NOMINMAX,_WIN32,_HAS_ITERATOR_DEBUGGING=0,_SECURE_SCL=0,_CRT_SECURE_NO_DEPRECATE,WB_USE_CGAL," />
			<Tool
				Name="VCMIDLTool"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="C:\hart\Wickbert\bin\$(OutDir)\Surface.lib."/>
		</Configuration>
	</Configurations>
	<Files>
			<File
				RelativePath="C:\hart\Wickbert\Surface\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule Surface.vcproj.cmake"
					CommandLine="&quot;C:\Program Files\CMake20\bin\cmake.exe&quot; C:\hart\Wickbert\Surface\CMakeLists.txt -HC:\hart\Wickbert -BC:\hart\Wickbert 

"
					AdditionalDependencies="C:\hart\Wickbert\CMakeLists.txt;C:\hart\Wickbert\CMakeSystem.cmake;C:\hart\Wickbert\CMakeCCompiler.cmake;C:\hart\Wickbert\CMakeCXXCompiler.cmake;&quot;C:\Program Files\CMake20\Modules\CMakeSystemSpecificInformation.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows-cl.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows-cl.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeDefaultMakeRuleVariables.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeBackwardCompatibilityC.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeVS7BackwardCompatibility.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeBackwardCompatibilityCXX.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\FindOpenGL.cmake&quot;;C:\hart\Wickbert\CMake\Modules\FindwxW.cmake;C:\hart\Wickbert\Surface\CMakeLists.txt;&quot;C:\Program Files\CMake20\Templates\CMakeWindowsSystemConfig.cmake&quot;;C:\hart\Wickbert\Surface\CMakeLists.txt;"
					Outputs="Surface.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule Surface.vcproj.cmake"
					CommandLine="&quot;C:\Program Files\CMake20\bin\cmake.exe&quot; C:\hart\Wickbert\Surface\CMakeLists.txt -HC:\hart\Wickbert -BC:\hart\Wickbert 

"
					AdditionalDependencies="C:\hart\Wickbert\CMakeLists.txt;C:\hart\Wickbert\CMakeSystem.cmake;C:\hart\Wickbert\CMakeCCompiler.cmake;C:\hart\Wickbert\CMakeCXXCompiler.cmake;&quot;C:\Program Files\CMake20\Modules\CMakeSystemSpecificInformation.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows-cl.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\Platform\Windows-cl.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeDefaultMakeRuleVariables.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeBackwardCompatibilityC.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeVS7BackwardCompatibility.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\CMakeBackwardCompatibilityCXX.cmake&quot;;&quot;C:\Program Files\CMake20\Modules\FindOpenGL.cmake&quot;;C:\hart\Wickbert\CMake\Modules\FindwxW.cmake;C:\hart\Wickbert\Surface\CMakeLists.txt;&quot;C:\Program Files\CMake20\Templates\CMakeWindowsSystemConfig.cmake&quot;;C:\hart\Wickbert\Surface\CMakeLists.txt;"
					Outputs="Surface.vcproj.cmake"/>
				</FileConfiguration>
			</File>
		<Filter
			Name="Surface"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Surface.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Surface.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\SurfParam.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\SurfParam.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Interval.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\itoa.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\itoa.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Box.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Box.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\IMatrix.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\IMatrix.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\KDTree.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\gmTNTconvert.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\gmTNTconvert.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\RandomStream.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\RandomStream.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\ThinPlateSpline.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\ThinPlateSpline.h">
			</File>
		</Filter>
		<Filter
			Name="OpenMesh"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\ClusterMesh.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\ClusterMesh.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\ClusterMeshTraits.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\OpenMeshUtility.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\ParticleMeshTraits.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\SurfaceMesh.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\TriMesh.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\OpenMesh\TriMesh.h">
			</File>
		</Filter>
		<Filter
			Name="Implicit"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Icosahedral.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Icosahedral.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Implicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Implicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\ImpFileManager.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\ImpFileManager.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\ITKImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\ITKImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\VTKImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\VTKImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\polygonizer.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\polygonizer.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\pixmaps.h">
			</File>
		</Filter>
		<Filter
			Name="Algebraic"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Algebraic.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Algebraic.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Cone.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Cone.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Cylinder.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Cylinder.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Ellipsoid.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Ellipsoid.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Quadric.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Quadric.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Torus.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Algebraic\Torus.h">
			</File>
		</Filter>
		<Filter
			Name="Geometric"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Geometric.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Plane.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Plane.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Point.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Point.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Segment.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Segment.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Sphere.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Geometric\Sphere.h">
			</File>
		</Filter>
		<Filter
			Name="Blob"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Blob\Blinn.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Blob\Blinn.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Blob\Blob.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Blob\Wyvill.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Blob\Wyvill.h">
			</File>
		</Filter>
		<Filter
			Name="MLS"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\AlexaImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\AlexaImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\Constants.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\Kernel.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\KolluriImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\KolluriImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\MLSSurface.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\MLSSurface.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\ProjNormImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\ProjNormImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\MLS\SpaceDef.h">
			</File>
		</Filter>
		<Filter
			Name="Operator"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ABlend.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\AIntersection.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ASubtraction.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\AUnion.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\BinaryOp.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\BinaryOp.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Blend.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Blend.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Blobby.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Blobby.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\CSGIntersection.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\CSGUnion.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Complement.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Complement.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Convolution.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\CSGIntersection.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\CSGUnion.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Convolution.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Difference.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Difference.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\DirectionalDerivative.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\DirectionalDerivative.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\GradFdotV.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\GradFdotV.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ImpList.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ImpList.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Intersection.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Intersection.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\KDOp.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\KDOp.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\KDTreeXin.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Mover.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Mover.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Offset.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Offset.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ParabolicPoints.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ParabolicPoints.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Product.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Product.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RFunction.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RadialCurvature.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RFunction.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RadialCurvature.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RotatedImplicit.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\RotatedImplicit.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\SpecularSurface.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\SpecularSurface.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Subtraction.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\SuggestiveSurface.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\SuggestiveSurface.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Sum.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Sum.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\UnaryOp.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\UnaryOp.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Union.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\Union.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ZeroGaussianCurvature.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Operator\ZeroGaussianCurvature.h">
			</File>
		</Filter>
		<Filter
			Name="Variational"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\AdaptiveCSRBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\AdaptiveCSRBF.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\AdaptiveCSRBF_Precomp.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\AdaptiveCSRBF_Precomp.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\CompactRBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\CompactRBF.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\InterfaceRBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\InterfaceRBF.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\MultiscaleCSRBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\MultiscaleCSRBF.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBF.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBFBasicFunctionsAndSelector.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBFBasicFunctionsAndSelector.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBFInterpolant.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\RBFInterpolant.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\SurfletCompactRBF.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\Variational\SurfletCompactRBF.h">
			</File>
		</Filter>
		<Filter
			Name="  DistanceField"
			Filter="">
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\adf.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\algo.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\bits.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\boundingvolume.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\cachingsparsescalarlattice.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\cell.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\defs.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\DistanceField.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\extractsurface.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\gltools.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\index.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\kdtree.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\matrix3d.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\mdsimhash.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\opengl.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\opengl_utils.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\particle.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\particleplacer.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\ray.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\renderable.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\scalar.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\scalarlattice.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\selectable.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\signeddistancetransform.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\sparsescalarlattice.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\spatialmap.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\stopwatch.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\tetmesh.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\triangle.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\triangleboxoverlap.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\trianglemesh2.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\trianglenearestpoint.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\utils.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\vector2d.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\vector3d.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\vector4d.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\viewwindow.h">
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\adf.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\DistanceField.cpp">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\sparsescalarlattice.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\cachingsparsescalarlattice.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\trianglemesh2.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\scalarlattice.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\triangle.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\boundingvolume.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\signeddistancetransform.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\trianglenearestpoint.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="C:\hart\Wickbert\Surface\Implicit\DistanceField\opengl_utils.cxx">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCLCompilerTool"
					AdditionalOptions=" /TP "
					/>
				</FileConfiguration>
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
